// Compiled shader for PC, Mac & Linux Standalone, uncompressed size: 15.1KB

Shader "Proland/Atmo/Sky" {
Properties {
 _Sun_Glare ("Sun Glare", 2D) = "black" {}
}
SubShader { 
 Tags { "QUEUE"="Background" "RenderType"="" }


 // Stats for Vertex shader:
 //       d3d11 : 10 math
 // Stats for Fragment shader:
 //       d3d11 : 162 math, 5 texture, 2 branch
 Pass {
  Tags { "QUEUE"="Background" "RenderType"="" }
  ZWrite Off
  Cull Off
Program "vp" {
SubProgram "d3d11 " {
// Stats: 10 math
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 384
Matrix 144 [_Globals_CameraToWorld]
Matrix 208 [_Globals_ScreenToCamera]
Matrix 320 [_Sun_WorldToLocal]
BindCB  "$Globals" 0
"vs_4_0
eefiecedlcindejcjibafomacbmhonlpccdhadaaabaaaaaaheadaaaaadaaaaaa
cmaaaaaakaaaaaaaciabaaaaejfdeheogmaaaaaaadaaaaaaaiaaaaaafaaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaafjaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaahaaaaaagaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apadaaaafaepfdejfeejepeoaaeoepfcenebemaafeeffiedepepfceeaaklklkl
epfdeheoiaaaaaaaaeaaaaaaaiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaa
aaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaa
heaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaaahaiaaaaheaaaaaaacaaaaaa
aaaaaaaaadaaaaaaadaaaaaaahaiaaaafdfgfpfaepfdejfeejepeoaafeeffied
epepfceeaaklklklfdeieefceeacaaaaeaaaabaajbaaaaaafjaaaaaeegiocaaa
aaaaaaaabhaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaaddcbabaaaacaaaaaa
ghaaaaaepccabaaaaaaaaaaaabaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaad
hccabaaaacaaaaaagfaaaaadhccabaaaadaaaaaagiaaaaacacaaaaaadgaaaaaf
dccabaaaaaaaaaaaegbabaaaaaaaaaaadgaaaaaimccabaaaaaaaaaaaaceaaaaa
aaaaaaaaaaaaaaaaaaaaiadpaaaaiadpdgaaaaafdccabaaaabaaaaaaegbabaaa
acaaaaaadiaaaaaihcaabaaaaaaaaaaafgbfbaaaaaaaaaaaegiccaaaaaaaaaaa
aoaaaaaadcaaaaakhcaabaaaaaaaaaaaegiccaaaaaaaaaaaanaaaaaaagbabaaa
aaaaaaaaegacbaaaaaaaaaaadcaaaaakhcaabaaaaaaaaaaaegiccaaaaaaaaaaa
apaaaaaakgbkbaaaaaaaaaaaegacbaaaaaaaaaaadcaaaaakhcaabaaaaaaaaaaa
egiccaaaaaaaaaaabaaaaaaapgbpbaaaaaaaaaaaegacbaaaaaaaaaaadiaaaaai
hcaabaaaabaaaaaafgafbaaaaaaaaaaaegiccaaaaaaaaaaaakaaaaaadcaaaaak
lcaabaaaaaaaaaaaegiicaaaaaaaaaaaajaaaaaaagaabaaaaaaaaaaaegaibaaa
abaaaaaadcaaaaakhcaabaaaaaaaaaaaegiccaaaaaaaaaaaalaaaaaakgakbaaa
aaaaaaaaegadbaaaaaaaaaaadgaaaaafhccabaaaacaaaaaaegacbaaaaaaaaaaa
diaaaaaihcaabaaaabaaaaaafgafbaaaaaaaaaaaegiccaaaaaaaaaaabfaaaaaa
dcaaaaaklcaabaaaaaaaaaaaegiicaaaaaaaaaaabeaaaaaaagaabaaaaaaaaaaa
egaibaaaabaaaaaadcaaaaakhccabaaaadaaaaaaegiccaaaaaaaaaaabgaaaaaa
kgakbaaaaaaaaaaaegadbaaaaaaaaaaadoaaaaab"
}
}
Program "fp" {
SubProgram "d3d11 " {
// Stats: 162 math, 5 textures, 2 branches
SetTexture 0 [_Sun_Glare] 2D 2
SetTexture 1 [_Sky_Inscatter] 2D 1
SetTexture 2 [_Sky_Transmittance] 2D 0
ConstBuffer "$Globals" 384
Float 16 [_Exposure]
Float 20 [scale]
Float 24 [Rg]
Float 28 [Rt]
Vector 48 [betaR] 3
Float 92 [mieG]
Float 112 [RES_R]
Float 116 [RES_MU]
Float 120 [RES_MU_S]
Float 124 [RES_NU]
Float 128 [_Sun_Intensity]
Vector 272 [_Globals_WorldCameraPos] 3
Vector 288 [_Globals_Origin] 3
Vector 304 [_Sun_WorldSunDir] 3
BindCB  "$Globals" 0
"ps_4_0
eefiecediooghjgbibehedkegiblmodlolpgkekdabaaaaaaaebiaaaaadaaaaaa
cmaaaaaaleaaaaaaoiaaaaaaejfdeheoiaaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadaaaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahahaaaaheaaaaaaacaaaaaaaaaaaaaaadaaaaaaadaaaaaaahahaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaklklklepfdeheocmaaaaaaabaaaaaa
aiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaafdfgfpfe
gbhcghgfheaaklklfdeieefcbebhaaaaeaaaaaaamfafaaaafjaaaaaeegiocaaa
aaaaaaaabeaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaaabaaaaaa
fkaaaaadaagabaaaacaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaafibiaaae
aahabaaaabaaaaaaffffaaaafibiaaaeaahabaaaacaaaaaaffffaaaagcbaaaad
hcbabaaaacaaaaaagcbaaaadhcbabaaaadaaaaaagfaaaaadpccabaaaaaaaaaaa
giaaaaacaiaaaaaabaaaaaahbcaabaaaaaaaaaaaegbcbaaaacaaaaaaegbcbaaa
acaaaaaaeeaaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaadiaaaaahhcaabaaa
aaaaaaaaagaabaaaaaaaaaaaegbcbaaaacaaaaaadbaaaaahicaabaaaaaaaaaaa
abeaaaaaaaaaaaaackbabaaaadaaaaaadcaaaaapdcaabaaaabaaaaaaegbabaaa
adaaaaaaaceaaaaaaaaaiaeaaaaaiaeaaaaaaaaaaaaaaaaaaceaaaaaaaaaaadp
aaaaaadpaaaaaaaaaaaaaaaaefaaaaajpcaabaaaabaaaaaaegaabaaaabaaaaaa
eghobaaaaaaaaaaaaagabaaaacaaaaaaabaaaaahhcaabaaaabaaaaaapgapbaaa
aaaaaaaaegacbaaaabaaaaaadeaaaaakhcaabaaaabaaaaaaegacbaaaabaaaaaa
aceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacpaaaaafhcaabaaaabaaaaaa
egacbaaaabaaaaaadiaaaaakhcaabaaaabaaaaaaegacbaaaabaaaaaaaceaaaaa
mnmmameamnmmameamnmmameaaaaaaaaabjaaaaafhcaabaaaabaaaaaaegacbaaa
abaaaaaadiaaaaaihcaabaaaabaaaaaaegacbaaaabaaaaaaagiacaaaaaaaaaaa
aiaaaaaaaaaaaaajhcaabaaaacaaaaaaegiccaaaaaaaaaaabbaaaaaaegiccaaa
aaaaaaaabcaaaaaadiaaaaaihcaabaaaacaaaaaaegacbaaaacaaaaaafgifcaaa
aaaaaaaaabaaaaaabaaaaaahicaabaaaaaaaaaaaegacbaaaacaaaaaaegacbaaa
acaaaaaaelaaaaafbcaabaaaadaaaaaadkaabaaaaaaaaaaabaaaaaahccaabaaa
adaaaaaaegacbaaaacaaaaaaegacbaaaaaaaaaaaaoaaaaahecaabaaaadaaaaaa
bkaabaaaadaaaaaaakaabaaaadaaaaaadcaaaaakicaabaaaaaaaaaaabkaabaaa
adaaaaaabkaabaaaadaaaaaadkaabaiaebaaaaaaaaaaaaaadiaaaaajicaabaaa
abaaaaaackiacaaaaaaaaaaaabaaaaaackiacaaaaaaaaaaaabaaaaaadcaaaaal
icaabaaaaaaaaaaadkiacaaaaaaaaaaaabaaaaaadkiacaaaaaaaaaaaabaaaaaa
dkaabaaaaaaaaaaaelaaaaaficaabaaaaaaaaaaadkaabaaaaaaaaaaaaaaaaaaj
icaabaaaaaaaaaaadkaabaiaebaaaaaaaaaaaaaabkaabaiaebaaaaaaadaaaaaa
deaaaaahicaabaaaaaaaaaaadkaabaaaaaaaaaaaabeaaaaaaaaaaaaadbaaaaah
icaabaaaacaaaaaaabeaaaaaaaaaaaaadkaabaaaaaaaaaaadcaaaaajhcaabaaa
aeaaaaaapgapbaaaaaaaaaaaegacbaaaaaaaaaaaegacbaaaacaaaaaaaaaaaaah
ccaabaaaafaaaaaadkaabaaaaaaaaaaabkaabaaaadaaaaaaaoaaaaaiecaabaaa
afaaaaaabkaabaaaafaaaaaadkiacaaaaaaaaaaaabaaaaaadhaaaaajhcaabaaa
acaaaaaapgapbaaaacaaaaaaegacbaaaaeaaaaaaegacbaaaacaaaaaadgaaaaag
bcaabaaaafaaaaaadkiacaaaaaaaaaaaabaaaaaadhaaaaajhcaabaaaadaaaaaa
pgapbaaaacaaaaaaegacbaaaafaaaaaaegacbaaaadaaaaaabnaaaaaiicaabaaa
aaaaaaaadkiacaaaaaaaaaaaabaaaaaaakaabaaaadaaaaaabaaaaaaibcaabaaa
aaaaaaaaegacbaaaaaaaaaaaegiccaaaaaaaaaaabdaaaaaabaaaaaaiccaabaaa
aaaaaaaaegacbaaaacaaaaaaegiccaaaaaaaaaaabdaaaaaaaoaaaaahccaabaaa
aaaaaaaabkaabaaaaaaaaaaaakaabaaaadaaaaaadcaaaaamecaabaaaaaaaaaaa
dkiacaaaaaaaaaaaabaaaaaadkiacaaaaaaaaaaaabaaaaaadkaabaiaebaaaaaa
abaaaaaaelaaaaafecaabaaaacaaaaaackaabaaaaaaaaaaadiaaaaahecaabaaa
aaaaaaaaakaabaaaadaaaaaaakaabaaaadaaaaaadcaaaaakicaabaaaabaaaaaa
akaabaaaadaaaaaaakaabaaaadaaaaaadkaabaiaebaaaaaaabaaaaaaelaaaaaf
icaabaaaabaaaaaadkaabaaaabaaaaaadcaaaaakecaabaaaaaaaaaaabkaabaaa
adaaaaaabkaabaaaadaaaaaackaabaiaebaaaaaaaaaaaaaadcaaaaalecaabaaa
aaaaaaaackiacaaaaaaaaaaaabaaaaaackiacaaaaaaaaaaaabaaaaaackaabaaa
aaaaaaaadbaaaaahicaabaaaadaaaaaabkaabaaaadaaaaaaabeaaaaaaaaaaaaa
dbaaaaahbcaabaaaaeaaaaaaabeaaaaaaaaaaaaackaabaaaaaaaaaaaabaaaaah
icaabaaaadaaaaaadkaabaaaadaaaaaaakaabaaaaeaaaaaaaoaaaaalhcaabaaa
aeaaaaaaaceaaaaaaaaaaadpaaaaaadpaaaaaadpaaaaaaaabgigcaaaaaaaaaaa
ahaaaaaaaaaaaaaiicaabaaaafaaaaaaakaabaiaebaaaaaaaeaaaaaaabeaaaaa
aaaaaadpdiaaaaahccaabaaaacaaaaaackaabaaaacaaaaaackaabaaaacaaaaaa
aaaaaaahicaabaaaacaaaaaaakaabaaaaeaaaaaaabeaaaaaaaaaaadpdgaaaaai
hcaabaaaafaaaaaaaceaaaaaaaaaiadpaaaaaaaaaaaaaaaaaaaaaaaadgaaaaaf
bcaabaaaacaaaaaaabeaaaaaaaaaialpdhaaaaajpcaabaaaafaaaaaapgapbaaa
adaaaaaaegaobaaaafaaaaaaegaobaaaacaaaaaaaoaaaaahbcaabaaaacaaaaaa
dkaabaaaabaaaaaackaabaaaacaaaaaaaoaaaaalocaabaaaacaaaaaaaceaaaaa
aaaaiadpaaaaiadpaaaaiadpaaaaiadpagijcaaaaaaaaaaaahaaaaaaaaaaaaal
ocaabaaaacaaaaaafgaobaiaebaaaaaaacaaaaaaaceaaaaaaaaaaaaaaaaaiadp
aaaaaadpaaaaiadpdcaaaaajbcaabaaaacaaaaaaakaabaaaacaaaaaabkaabaaa
acaaaaaabkaabaaaaeaaaaaaaaaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaa
bkaabaaaafaaaaaaelaaaaafecaabaaaaaaaaaaackaabaaaaaaaaaaadcaaaaaj
ecaabaaaaaaaaaaabkaabaaaadaaaaaaakaabaaaafaaaaaackaabaaaaaaaaaaa
aaaaaaahicaabaaaabaaaaaadkaabaaaabaaaaaackaabaaaafaaaaaaaoaaaaah
ecaabaaaaaaaaaaackaabaaaaaaaaaaadkaabaaaabaaaaaadcaaaaajecaabaaa
aaaaaaaackaabaaaaaaaaaaackaabaaaacaaaaaadkaabaaaafaaaaaadeaaaaah
ccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaahbdneklodiaaaaahccaabaaa
aaaaaaaabkaabaaaaaaaaaaaabeaaaaabodakleaddaaaaaiicaabaaaabaaaaaa
bkaabaiaibaaaaaaaaaaaaaaabeaaaaaaaaaiadpdeaaaaaiccaabaaaacaaaaaa
bkaabaiaibaaaaaaaaaaaaaaabeaaaaaaaaaiadpaoaaaaakccaabaaaacaaaaaa
aceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaiadpbkaabaaaacaaaaaadiaaaaah
icaabaaaabaaaaaadkaabaaaabaaaaaabkaabaaaacaaaaaadiaaaaahccaabaaa
acaaaaaadkaabaaaabaaaaaadkaabaaaabaaaaaadcaaaaajecaabaaaacaaaaaa
bkaabaaaacaaaaaaabeaaaaafpkokkdmabeaaaaadgfkkolndcaaaaajecaabaaa
acaaaaaabkaabaaaacaaaaaackaabaaaacaaaaaaabeaaaaaochgdidodcaaaaaj
ecaabaaaacaaaaaabkaabaaaacaaaaaackaabaaaacaaaaaaabeaaaaaaebnkjlo
dcaaaaajccaabaaaacaaaaaabkaabaaaacaaaaaackaabaaaacaaaaaaabeaaaaa
diphhpdpdiaaaaahecaabaaaacaaaaaadkaabaaaabaaaaaabkaabaaaacaaaaaa
dbaaaaaiccaabaaaadaaaaaaabeaaaaaaaaaiadpbkaabaiaibaaaaaaaaaaaaaa
dcaaaaajecaabaaaacaaaaaackaabaaaacaaaaaaabeaaaaaaaaaaamaabeaaaaa
nlapmjdpabaaaaahecaabaaaacaaaaaabkaabaaaadaaaaaackaabaaaacaaaaaa
dcaaaaajicaabaaaabaaaaaadkaabaaaabaaaaaabkaabaaaacaaaaaackaabaaa
acaaaaaaddaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaaaaaaiadp
dbaaaaaiccaabaaaaaaaaaaabkaabaaaaaaaaaaabkaabaiaebaaaaaaaaaaaaaa
dhaaaaakccaabaaaaaaaaaaabkaabaaaaaaaaaaadkaabaiaebaaaaaaabaaaaaa
dkaabaaaabaaaaaadcaaaaajccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaa
colkgidpabeaaaaakehadndpdiaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaa
abeaaaaaaaaaaadpdcaaaaajccaabaaaaaaaaaaabkaabaaaaaaaaaaadkaabaaa
acaaaaaackaabaaaaeaaaaaaaaaaaaahicaabaaaabaaaaaaakaabaaaaaaaaaaa
abeaaaaaaaaaiadpdiaaaaahicaabaaaabaaaaaadkaabaaaabaaaaaaabeaaaaa
aaaaaadpaaaaaaaiccaabaaaacaaaaaadkiacaaaaaaaaaaaahaaaaaaabeaaaaa
aaaaialpdiaaaaahecaabaaaacaaaaaadkaabaaaabaaaaaabkaabaaaacaaaaaa
diaaaaaiicaabaaaacaaaaaaakaabaaaacaaaaaaakiacaaaaaaaaaaaahaaaaaa
dcaaaaakbcaabaaaacaaaaaaakaabaaaacaaaaaaakiacaaaaaaaaaaaahaaaaaa
abeaaaaaaaaaialpebaaaaaffcaabaaaacaaaaaaagacbaaaacaaaaaaaoaaaaai
bcaabaaaacaaaaaaakaabaaaacaaaaaaakiacaaaaaaaaaaaahaaaaaaebaaaaaf
ccaabaaaadaaaaaadkaabaaaacaaaaaaaoaaaaaiccaabaaaadaaaaaabkaabaaa
adaaaaaaakiacaaaaaaaaaaaahaaaaaaaaaaaaahccaabaaaaaaaaaaabkaabaaa
aaaaaaaackaabaaaacaaaaaaaoaaaaaiccaabaaaaeaaaaaabkaabaaaaaaaaaaa
dkiacaaaaaaaaaaaahaaaaaaaoaaaaaiecaabaaaaaaaaaaackaabaaaaaaaaaaa
akiacaaaaaaaaaaaahaaaaaaaaaaaaahecaabaaaaeaaaaaaakaabaaaacaaaaaa
ckaabaaaaaaaaaaaefaaaaajpcaabaaaafaaaaaajgafbaaaaeaaaaaaeghobaaa
abaaaaaaaagabaaaabaaaaaaaaaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaa
abeaaaaaaaaaiadpaoaaaaaibcaabaaaaeaaaaaabkaabaaaaaaaaaaadkiacaaa
aaaaaaaaahaaaaaaefaaaaajpcaabaaaagaaaaaaigaabaaaaeaaaaaaeghobaaa
abaaaaaaaagabaaaabaaaaaaaaaaaaahicaabaaaaeaaaaaabkaabaaaadaaaaaa
ckaabaaaaaaaaaaaefaaaaajpcaabaaaahaaaaaangafbaaaaeaaaaaaeghobaaa
abaaaaaaaagabaaaabaaaaaaefaaaaajpcaabaaaaeaaaaaamgaabaaaaeaaaaaa
eghobaaaabaaaaaaaagabaaaabaaaaaabpaaaeaddkaabaaaaaaaaaaadcaaaaak
ccaabaaaaaaaaaaadkaabaaaabaaaaaabkaabaaaacaaaaaackaabaiaebaaaaaa
acaaaaaabkaaaaafecaabaaaaaaaaaaadkaabaaaacaaaaaaaaaaaaaiicaabaaa
aaaaaaaabkaabaiaebaaaaaaaaaaaaaaabeaaaaaaaaaiadpdiaaaaahpcaabaaa
acaaaaaafgafbaaaaaaaaaaaegaobaaaagaaaaaadcaaaaajpcaabaaaacaaaaaa
egaobaaaafaaaaaapgapbaaaaaaaaaaaegaobaaaacaaaaaadiaaaaahpcaabaaa
aeaaaaaafgafbaaaaaaaaaaaegaobaaaaeaaaaaadcaaaaajpcaabaaaaeaaaaaa
egaobaaaahaaaaaapgapbaaaaaaaaaaaegaobaaaaeaaaaaaaaaaaaaiccaabaaa
aaaaaaaackaabaiaebaaaaaaaaaaaaaaabeaaaaaaaaaiadpdiaaaaahpcaabaaa
aeaaaaaakgakbaaaaaaaaaaaegaobaaaaeaaaaaadcaaaaajpcaabaaaacaaaaaa
egaobaaaacaaaaaafgafbaaaaaaaaaaaegaobaaaaeaaaaaaaaaaaaajccaabaaa
aaaaaaaaakaabaaaadaaaaaackiacaiaebaaaaaaaaaaaaaaabaaaaaaaaaaaaak
ecaabaaaaaaaaaaackiacaiaebaaaaaaaaaaaaaaabaaaaaadkiacaaaaaaaaaaa
abaaaaaaaoaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaackaabaaaaaaaaaaa
elaaaaafccaabaaaadaaaaaabkaabaaaaaaaaaaaaaaaaaahccaabaaaaaaaaaaa
ckaabaaaadaaaaaaabeaaaaajkjjbjdodiaaaaahccaabaaaaaaaaaaabkaabaaa
aaaaaaaaabeaaaaajfdbeeebddaaaaaiecaabaaaaaaaaaaabkaabaiaibaaaaaa
aaaaaaaaabeaaaaaaaaaiadpdeaaaaaiicaabaaaaaaaaaaabkaabaiaibaaaaaa
aaaaaaaaabeaaaaaaaaaiadpaoaaaaakicaabaaaaaaaaaaaaceaaaaaaaaaiadp
aaaaiadpaaaaiadpaaaaiadpdkaabaaaaaaaaaaadiaaaaahecaabaaaaaaaaaaa
dkaabaaaaaaaaaaackaabaaaaaaaaaaadiaaaaahicaabaaaaaaaaaaackaabaaa
aaaaaaaackaabaaaaaaaaaaadcaaaaajicaabaaaabaaaaaadkaabaaaaaaaaaaa
abeaaaaafpkokkdmabeaaaaadgfkkolndcaaaaajicaabaaaabaaaaaadkaabaaa
aaaaaaaadkaabaaaabaaaaaaabeaaaaaochgdidodcaaaaajicaabaaaabaaaaaa
dkaabaaaaaaaaaaadkaabaaaabaaaaaaabeaaaaaaebnkjlodcaaaaajicaabaaa
aaaaaaaadkaabaaaaaaaaaaadkaabaaaabaaaaaaabeaaaaadiphhpdpdiaaaaah
icaabaaaabaaaaaadkaabaaaaaaaaaaackaabaaaaaaaaaaadbaaaaaiecaabaaa
adaaaaaaabeaaaaaaaaaiadpbkaabaiaibaaaaaaaaaaaaaadcaaaaajicaabaaa
abaaaaaadkaabaaaabaaaaaaabeaaaaaaaaaaamaabeaaaaanlapmjdpabaaaaah
icaabaaaabaaaaaackaabaaaadaaaaaadkaabaaaabaaaaaadcaaaaajecaabaaa
aaaaaaaackaabaaaaaaaaaaadkaabaaaaaaaaaaadkaabaaaabaaaaaaddaaaaah
ccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaaaaaaiadpdbaaaaaiccaabaaa
aaaaaaaabkaabaaaaaaaaaaabkaabaiaebaaaaaaaaaaaaaadhaaaaakccaabaaa
aaaaaaaabkaabaaaaaaaaaaackaabaiaebaaaaaaaaaaaaaackaabaaaaaaaaaaa
diaaaaahbcaabaaaadaaaaaabkaabaaaaaaaaaaaabeaaaaaklkkckdpeiaaaaal
pcaabaaaadaaaaaaegaabaaaadaaaaaaeghobaaaacaaaaaaaagabaaaaaaaaaaa
abeaaaaaaaaaaaaadiaaaaahocaabaaaaaaaaaaapgapbaaaacaaaaaaagajbaaa
acaaaaaadeaaaaahicaabaaaabaaaaaaakaabaaaacaaaaaaabeaaaaabhlhnbdi
aoaaaaahocaabaaaaaaaaaaafgaobaaaaaaaaaaapgapbaaaabaaaaaaaoaaaaaj
hcaabaaaaeaaaaaaagiacaaaaaaaaaaaadaaaaaaegiccaaaaaaaaaaaadaaaaaa
diaaaaahocaabaaaaaaaaaaafgaobaaaaaaaaaaaagajbaaaaeaaaaaadcaaaaaj
icaabaaaabaaaaaaakaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaaaaaiadp
diaaaaahicaabaaaacaaaaaadkaabaaaabaaaaaaabeaaaaaefhghedndcaaaaam
icaabaaaadaaaaaadkiacaiaebaaaaaaaaaaaaaaafaaaaaadkiacaaaaaaaaaaa
afaaaaaaabeaaaaaaaaaiadpdiaaaaahicaabaaaadaaaaaadkaabaaaadaaaaaa
abeaaaaaefhgpedndcaaaaaodcaabaaaaeaaaaaapgipcaaaaaaaaaaaafaaaaaa
pgipcaaaaaaaaaaaafaaaaaaaceaaaaaaaaaiadpaaaaaaeaaaaaaaaaaaaaaaaa
apaaaaaibcaabaaaaaaaaaaaagaabaaaaaaaaaaapgipcaaaaaaaaaaaafaaaaaa
aaaaaaaibcaabaaaaaaaaaaaakaabaiaebaaaaaaaaaaaaaaakaabaaaaeaaaaaa
cpaaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaadiaaaaahbcaabaaaaaaaaaaa
akaabaaaaaaaaaaaabeaaaaaaaaamalpbjaaaaafbcaabaaaaaaaaaaaakaabaaa
aaaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaadkaabaaaadaaaaaa
diaaaaahbcaabaaaaaaaaaaadkaabaaaabaaaaaaakaabaaaaaaaaaaaaoaaaaah
bcaabaaaaaaaaaaaakaabaaaaaaaaaaabkaabaaaaeaaaaaadiaaaaahhcaabaaa
aaaaaaaaagaabaaaaaaaaaaajgahbaaaaaaaaaaadcaaaaajhcaabaaaaaaaaaaa
egacbaaaacaaaaaapgapbaaaacaaaaaaegacbaaaaaaaaaaabcaaaaabdgaaaaai
hcaabaaaadaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaaaaadgaaaaai
hcaabaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabfaaaaab
diaaaaaihcaabaaaaaaaaaaaegacbaaaaaaaaaaaagiacaaaaaaaaaaaaiaaaaaa
dcaaaaajhcaabaaaaaaaaaaaegacbaaaabaaaaaaegacbaaaadaaaaaaegacbaaa
aaaaaaaadiaaaaaihcaabaaaaaaaaaaaegacbaaaaaaaaaaaagiacaaaaaaaaaaa
abaaaaaadbaaaaakhcaabaaaabaaaaaaegacbaaaaaaaaaaaaceaaaaacpnnledp
cpnnledpcpnnledpaaaaaaaadiaaaaakpcaabaaaacaaaaaaagafbaaaaaaaaaaa
aceaaaaanmcomedodlkklilpnmcomedodlkklilpcpaaaaafdcaabaaaaaaaaaaa
igaabaaaacaaaaaadiaaaaakdcaabaaaaaaaaaaaegaabaaaaaaaaaaaaceaaaaa
cplkoidocplkoidoaaaaaaaaaaaaaaaabjaaaaafdcaabaaaaaaaaaaaegaabaaa
aaaaaaaabjaaaaafdcaabaaaacaaaaaangafbaaaacaaaaaaaaaaaaaldcaabaaa
acaaaaaaegaabaiaebaaaaaaacaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaaaaa
aaaaaaaadhaaaaajdccabaaaaaaaaaaaegaabaaaabaaaaaaegaabaaaaaaaaaaa
egaabaaaacaaaaaadiaaaaakdcaabaaaaaaaaaaakgakbaaaaaaaaaaaaceaaaaa
nmcomedodlkklilpaaaaaaaaaaaaaaaacpaaaaafbcaabaaaaaaaaaaaakaabaaa
aaaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaacplkoido
bjaaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaabjaaaaafccaabaaaaaaaaaaa
bkaabaaaaaaaaaaaaaaaaaaiccaabaaaaaaaaaaabkaabaiaebaaaaaaaaaaaaaa
abeaaaaaaaaaiadpdhaaaaajeccabaaaaaaaaaaackaabaaaabaaaaaaakaabaaa
aaaaaaaabkaabaaaaaaaaaaadgaaaaaficcabaaaaaaaaaaaabeaaaaaaaaaiadp
doaaaaab"
}
}
 }
}
}